[tool.poetry]
name = "ws-petproject"
version = "0.1.0"


[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"
celery = "^5.3.5"
redis = "^5.0.1"
djangorestframework = "^3.14.0"
fastapi = "^0.104.1"
pymongo = "^4.6.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.2"
flake8 = "^6.1.0"
mypy = "^1.7.0"
isort = "^5.12.0"
black = "^23.11.0"

